services:
  order-service:
    build:
      context: ./services/order
    container_name: order-service
    ports:
      - "3003:3003"
    environment:
      DB_HOST: host.docker.internal # Menggunakan XAMPP MySQL
      DB_USER: root
      DB_PASSWORD: ""
      RABBITMQ_HOST: ${RABBITMQ_HOST:-localhost}
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      PORT: ${ORDER_SERVICE_PORT:-3003}
    networks:
      - simtech-network

  payment-service:
    build:
      context: ./services/payment
    container_name: payment-service
    ports:
      - "3004:3004"
    environment:
      DB_HOST: host.docker.internal # Menggunakan XAMPP MySQL
      DB_USER: root
      DB_PASSWORD: ""
      RABBITMQ_HOST: ${RABBITMQ_HOST:-localhost}
      RABBITMQ_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-guest}
      PORT: ${PAYMENT_SERVICE_PORT:-3004}
    networks:
      - simtech-network

  product-service:
    build:
      context: ./services/product
    container_name: product-service
    ports:
      - "3002:3002"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: ""
      PORT: 3002
    networks:
      - simtech-network

  user-service:
    build:
      context: ./services/user
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      DB_HOST: host.docker.internal # Menggunakan XAMPP MySQL
      DB_USER: root
      DB_PASSWORD: ""
      PORT: 3001
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-your-google-client-id}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-your-google-client-secret}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL:-q}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-your-github-client-id}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-your-github-client-secret}
      GITHUB_CALLBACK_URL: ${GITHUB_CALLBACK_URL:-https://5081-182-3-43-40.ngrok-free.app/auth/github/callback}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - simtech-network

  gateway-service:
    build:
      context: ./services/gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      ORDER_SERVICE_URL: http://order-service:3003
      PAYMENT_SERVICE_URL: http://payment-service:3004
      PRODUCT_SERVICE_URL: http://product-service:3002
      USER_SERVICE_URL: http://user-service:3001
      HTTP_PORT: 8080
      HTTPS_PORT: 8443
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - simtech-network
    volumes:
      - ./services/gateway:/app

networks:
  simtech-network:
    driver: bridge
